import Head from "next/head";
import Hero from "../components/hero/hero";
import PopularProducts from "../components/popularProducts/popularProducts";
import Header from "../layout/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <PopularProducts />
    </div>
  );
}
